apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-pv
  labels:
    app: navidrome
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"